In [1]:
import numpy as np

In [15]:
c=np.array([[1,2],[3,4],[5,6]])
# print(c)
print(c.ndim)

2


In [16]:
d=np.arange(10)
print(d)
print(d.ndim)

[0 1 2 3 4 5 6 7 8 9]
1


In [14]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
# print(b)
# Get dimension
print(b.ndim)

2


In [17]:
b.dtype

dtype('float64')

In [18]:
b.shape

(2, 3)

In [19]:
b[1,2]

4.0

In [22]:
#Get specific row
b[1,:]

array([6., 5., 4.])

In [21]:
#Get a specific column
b[:,0]

array([9., 6.])

In [23]:
b[1,0:1:2]

array([6.])